image: Visual Studio 2017
clone_depth: 1
version: '{build}-{branch}'
skip_branch_with_pr: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- %PYTHON%\\python.exe -m pip install hypothesis Cython wheel
- git config core.symlinks true
- git submodule init
- git submodule update
- git reset --hard

build_script:
- %PYTHON%\\python.exe setup.py build_ext -i
- set HYPOTHESIS_PROFILE=ci
- %PYTHON%\\python.exe test.py
- set HYPOTHESIS_PROFILE=
- %PYTHON%\\python.exe -c "import cydoctest, pyroaring; cydoctest.testmod(pyroaring)" -v
- git clean -xfd
# Testing several installation methods.
- %PYTHON%\\python.exe setup.py bdist_wheel
- %PYTHON%\\python.exe -m pip install dist/pyroaring*.whl
- %PYTHON%\\python.exe test.py
- %PYTHON%\\python.exe -m pip uninstall -y pyroaring
- git clean -xfd
- %PYTHON%\\python.exe setup.py sdist
- pip install dist/pyroaring*.tar.gz
- %PYTHON%\\python.exe test.py

before_deploy:
- %PYTHON%\\python.exe setup.py bdist_wheel
- %PYTHON%\\python.exe setup.py sdist
- dir dist

artifacts:
- path: dist
  name: wheels