image: Visual Studio 2017
clone_depth: 1
version: '{build}-{branch}'
skip_branch_with_pr: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      BITS: 32
    - PYTHON: "C:\\Python34"
      BITS: 32
    - PYTHON: "C:\\Python35"
      BITS: 32
    - PYTHON: "C:\\Python27-x64"
      BITS: 64
    - PYTHON: "C:\\Python34-x64"
      BITS: 64
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
      BITS: 64
    - PYTHON: "C:\\Python36-x64"
      BITS: 64

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"
  - set PATH=C:\%PYTHON%\scripts;C:\%PYTHON%;%PATH%
  - echo %PATH%
  - pip install hypothesis Cython wheel
  - git config core.symlinks true
  - git reset --hard
  - git submodule init
  - git submodule update

build: off

test_script:
  - python setup.py build_ext -i
  - set HYPOTHESIS_PROFILE=ci
  - python test.py
  - set HYPOTHESIS_PROFILE=
  - python -c "import cydoctest, pyroaring; cydoctest.testmod(pyroaring)" -v
  - git clean -xfd
  # Testing several installation methods.
  - python setup.py bdist_wheel
  - pip install dist/pyroaring*.whl
  - python test.py
  - pip uninstall -y pyroaring
  - git clean -xfd
  - python setup.py sdist
  - pip install dist/pyroaring*.tar.gz
  - python test.py

after_test:
  - python setup.py bdist_wheel
  - python setup.py sdist
  - dir dist

artifacts:
  - path: dist\*