clone_depth: 1
version: '{build}-{branch}'
skip_branch_with_pr: false

install:
- set PATH=C:\Python27-x64\scripts;C:\Python27-x64;C:\Python35-x64\scripts;C:\Python35-x64;%PATH%
- pip install hypothesis Cython
- git config core.symlinks true
- git reset --hard
- git submodule init
- git submodule update

build_script:
- python setup.py build_ext -i
- HYPOTHESIS_PROFILE=ci python test.py
- python -c "import cydoctest, pyroaring; cydoctest.testmod(pyroaring)" -v
