image: Visual Studio 2017
clone_depth: 1
version: '{build}-{branch}'
skip_branch_with_pr: false
configuration: Release

environment:
  matrix:
    - py_version: 27
    - py_version: 34
    - py_version: 35
    - py_version: 36

platform:
  - x64

install:
  - set "PYTHON=C:\\Python%py_version%"
  - IF "%PLATFORM%" == "x64" ( set "PYTHON=%PYTHON%-x64" )
  - IF "%PLATFORM%" == "x64" ( set "vcvarsall_arg=amd64" ) ELSE ( set "vcvarsall_arg=x86" )
  - IF "%py_version%" == "34" ( set "DISTUTILS_USE_SDK=1" )
  - set "PATH=%PYTHON%\\scripts;%PYTHON%;%PATH%"
  - "%PYTHON%\\python.exe -m pip install --upgrade setuptools"
  - "%PYTHON%\\python.exe -m pip install hypothesis Cython wheel"
  - git config core.symlinks true
  - git reset --hard
  - git submodule init
  - git submodule update
  - "%PYTHON%\\python.exe  setup.py build_ext -i"

build: off

artifacts:
  - path: dist\*
