image: Visual Studio 2017
clone_depth: 1
version: '{build}-{branch}'
skip_branch_with_pr: false

install:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- set PATH=C:\Python36-x64\scripts;C:\Python36-x64;%PATH%
- pip install hypothesis Cython
- git config core.symlinks true
- git submodule init
- git submodule update
- git reset --hard

build_script:
- python setup.py build_ext -i
- HYPOTHESIS_PROFILE=ci python test.py
- python -c "import cydoctest, pyroaring; cydoctest.testmod(pyroaring)" -v
