clone_depth: 1
version: '{build}-{branch}'
skip_branch_with_pr: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - ps: |
      if ($env:PYTHON -match "Python27") {
        Invoke-WebRequest https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi -OutFile vc27.msi
        msiexec /q /i vc27.msi
      }
  - cmd: |
      IF "%PYTHON:~12,3%"=="x64" (
        call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
      ) ELSE (
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
      )
  - "%PYTHON%\\python.exe -m pip install --upgrade setuptools"
  - "%PYTHON%\\python.exe -m pip install hypothesis Cython wheel"
  - git config core.symlinks true
  - git reset --hard
  - git submodule init
  - git submodule update

build: off

test_script:
  # Run tests (note ci profile takes a while)
  - "build.cmd %PYTHON%\\python.exe setup.py build_ext -i"
  - set HYPOTHESIS_PROFILE=ci
  - "%PYTHON%\\python.exe test.py"
  - set HYPOTHESIS_PROFILE=dev
  - '%PYTHON%\\python.exe -c "import cydoctest, pyroaring; cydoctest.testmod(pyroaring)" -v'
  - git clean -xfd
  # Test installation from binary wheel
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
  - for %%f in (dist\pyroaring*.whl) do (pip install %%~f)
  - "%PYTHON%\\python.exe test.py"
  - "%PYTHON%\\python.exe -m pip uninstall -y pyroaring"
  - git clean -xfd
  # Test installation from source distribution
  - "build.cmd %PYTHON%\\python.exe setup.py sdist"
  - for %%f in (dist\pyroaring*.tar.gz) do (pip install %%~f)
  - "%PYTHON%\\python.exe test.py"
  - "%PYTHON%\\python.exe -m pip uninstall -y pyroaring"
  - git clean -xfd

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
  - "build.cmd %PYTHON%\\python.exe setup.py sdist"
  - dir dist

artifacts:
  - path: dist\*